### ISSUE TITLE
Error after Queuing in Classic LFGBrowser

### ISSUE THREAD

**Issue by PJai** [gk646/GearScoreClassic#10]
When queuing in 1.15.5.57716 Anniversary Realms, the addon throws an error after listing yourself for a dungeon and you cannot browse groups anymore in the finder.

Error:
6x [ADDON_ACTION_BLOCKED] AddOn 'GearScoreClassic+' tried to call the protected function 'Search()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Search'
[string "@Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Browse.lua"]:250: in function `LFGBrowse_DoSearch'
[string "@Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Browse.lua"]:189: in function `SearchActiveEntry'
[string "@Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_ParentFrame.lua"]:95: in function `LFGParentFrame_SearchActiveEntry'
[string "@Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Listing.lua"]:77: in function <...pFinder_VanillaStyle/Blizzard_LFGVanilla_Listing.lua:54>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**Comment by gk646** [comment]
Hey,
thanks for the report!
Sadly i dont have the capacity to update this plugin anymore. Ill mark it as such.
However this plugin was made to fix a bug with scaling in SOD. Since your playing the new Classic servers you do not have low level Epic items (what caused the bug).
I recommend switching over to the other popular [GearScore](https://www.curseforge.com/wow/addons/tacotip-gearscore-talents) plugin!
Thanks for using GearScoreClassic!
